service: login

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    USER_POOL_ID: "us-east-1_zQitSgr2g"
    CLIENT_ID: "2cu6nb45dknrkvtvre202906q8"

functions: 
  signup: 
    handler: handler.signup
    events:
      - http:
          path: signup
          method: post
          cors: true
          request: 
            template:
              application/json: '{
                  "name": "$input.params(''name'')",
                  "emailAddress": "$input.params(''emailAddress'')",
                  "password": "$input.params(''password'')"
              }'

  confirm-account:
    handler: handler.confirmAccount
    events: 
      - http:
          path: confirm-account
          method: post
          cors: true
          request:
            template:
              application/json: '{
                "username": "$input.params(''username'')",
                "confirmationCode": "$input.params(''confirmationCode'')"
              }'
    
  login:
    handler: handler.login
    events:
      - http:
          path: login
          method: post
          cors: true
          request: 
            template:
              application/json: '{
                  "name": "$input.params(''name''",
                  "emailAddress": "$input.params(''emailAddress'')",
                  "password": "$input.password"
              }'

